name: 'Deploy Hugo to Remote'
description: '🚀 Build and deploy a Hugo site to a remote repository with latest extended Hugo.'
author: 'victoriadrake'
branding:
  icon: 'send'
  color: 'blue'
inputs:
  branch:
    description: "The branch of your remote repository to deploy to. Defaults to 'master'"
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
