name: 'Deploy Hugo to Remote'
description: '🚀 Build and deploy a Hugo site to a remote repository with latest extended Hugo.'
author: 'victoriadrake'
branding:
  icon: 'send'
  color: 'blue'
inputs:
  branch:
    description: "which branch of remote repo will be deploy. Default: master"
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'